[package]
name = "rustdatabaseinfo"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
postgres = { version = "0.19.12", features = ["with-chrono-0_4"] }
postgres-native-tls = "0.5"
native-tls = "0.2"
